#ifndef OPERATE_REG_H
#define OPERATE_REG_H

#include "crc.h"
#include "packet_sr.h"
/*Register operations for camera image data include initialization, query, and modification*/

/*axi_tpg*/
#define VIDEO_TPG_BASEADDRESS     0x46200000
#define VIDEO_TPG_EN_REG        (VIDEO_TPG_BASEADDRESS+0x4C)
#define VIDEO_TPG_CHANNEL_REG    (VIDEO_TPG_BASEADDRESS+0x50)
#define VIDEO_TPG_ROLL_REG        (VIDEO_TPG_BASEADDRESS+0x54)
#define VIDEO_TPG_MODE_REG        (VIDEO_TPG_BASEADDRESS+0x58)
#define VIDEO_TPG_HIGH_REG        (VIDEO_TPG_BASEADDRESS+0x5C)
#define VIDEO_TPG_WIDTH_REG        (VIDEO_TPG_BASEADDRESS+0x60)

/*axi_capture_ctl*/
#define VIDEO_CAPTURE_CTRL_BASEADDRESS             0x46201000
#define VIDEO_CAPTURE_CTRL_ENB_REG                 (VIDEO_CAPTURE_CTRL_BASEADDRESS+0x00)
#define VIDEO_CAPTURE_CTRL_FGROUP_ENB_REG         (VIDEO_CAPTURE_CTRL_BASEADDRESS+0x08)
#define VIDEO_CAPTURE_CTRL_FGROUP_SIZE_REG        (VIDEO_CAPTURE_CTRL_BASEADDRESS+0x0C)
#define VIDEO_CAPTURE_CTRL_FGROUP_MODE_REG        (VIDEO_CAPTURE_CTRL_BASEADDRESS+0x10)
#define VIDEO_CAPTURE_CTRL_FGROUP_OVERLAP_REG    (VIDEO_CAPTURE_CTRL_BASEADDRESS+0x14)

/*axi_video_s2mm*/
#define VIDEO_S2MM_BASEADDRESS         0x46202000
#define VIDEO_S2MM_RUN_REG          (VIDEO_S2MM_BASEADDRESS+0x00)
#define VIDEO_S2MM_VSIZE_REG        (VIDEO_S2MM_BASEADDRESS+0x40)
#define VIDEO_S2MM_HSIZE_REG        (VIDEO_S2MM_BASEADDRESS+0x44)
#define VIDEO_S2MM_HSTRIDE_REG      (VIDEO_S2MM_BASEADDRESS+0x48)

/*axi_video_intr_gen*/
#define VIDEO_INTR_GEN_BASEADDRESS             0x46203000
#define VIDEO_INTR_GEN_HOST_READY_REG         (VIDEO_INTR_GEN_BASEADDRESS+0x00)
#define VIDEO_INTR_GEN_INTR_TIME_REG         (VIDEO_INTR_GEN_BASEADDRESS+0x04)
#define VIDEO_INTR_GEN_INTR_THRESHOLD_REG     (VIDEO_INTR_GEN_BASEADDRESS+0x08)
#define VIDEO_INTR_GEN_FIFO_LENGTH_REG         (VIDEO_INTR_GEN_BASEADDRESS+0x10)
#define VIDEO_INTR_GEN_S2MM_VSIZE_REG         (VIDEO_INTR_GEN_BASEADDRESS+0x30)
#define VIDEO_INTR_GEN_S2MM_HSTRIDE_REG     (VIDEO_INTR_GEN_BASEADDRESS+0x34)
#define VIDEO_INTR_GEN_HOST_READY_TIME_REG     (VIDEO_INTR_GEN_BASEADDRESS+0x60)


/*axi_cameralink_receive*/
#define CAMERAIF_CAMERALINK_RECEI_BASEADDRESS             0x46012000
#define CAMERAIF_CAMERALINK_RECEI_SOFT_RESET_PULSE_REG  (CAMERAIF_CAMERALINK_RECEI_BASEADDRESS+0x00)
#define CAMERAIF_CAMERALINK_RECEI_CL_CONFIGURATION_REG  (CAMERAIF_CAMERALINK_RECEI_BASEADDRESS+0x08)
#define CAMERAIF_CAMERALINK_RECEI_CL_TAP_SIZE_REG          (CAMERAIF_CAMERALINK_RECEI_BASEADDRESS+0x0C)
#define CAMERAIF_CAMERALINK_RECEI_CL_TAP_NUMBER_REG      (CAMERAIF_CAMERALINK_RECEI_BASEADDRESS+0x10)
#define CAMERAIF_CAMERALINK_RECEI_RX_RESET_REG          (CAMERAIF_CAMERALINK_RECEI_BASEADDRESS+0x14)
#define CAMERAIF_CAMERALINK_RECEI_USE_DVAL_REG          (CAMERAIF_CAMERALINK_RECEI_BASEADDRESS+0x18)
#define CAMERAIF_CAMERALINK_RECEI_USE_FVAL_REG          (CAMERAIF_CAMERALINK_RECEI_BASEADDRESS+0x1C)

/*axi_cl_ccx*/
#define CAMERAIF_CL_CCX_BASEADDRESS 0x46013000
#define CAMERAIF_CL_CCX_START_REG     (CAMERAIF_CL_CCX_BASEADDRESS+0x14)
#define CAMERAIF_CL_CCX_STOP_REG     (CAMERAIF_CL_CCX_BASEADDRESS+0x18)
#define CAMERAIF_CL_CCX_FREQ_REG     (CAMERAIF_CL_CCX_BASEADDRESS+0x1C)

/*cameraif_uart_top*/
#define CAMERAIF_UART_TOP_BASEADDRESS             0x46010000
#define CAMERAIF_UART_TOP_INTR_ACK_REG             (CAMERAIF_UART_TOP_BASEADDRESS+0x44)
#define CAMERAIF_UART_TOP_REG_READDATA_REG         (CAMERAIF_UART_TOP_BASEADDRESS+0x4C)
#define CAMERAIF_UART_TOP_AXI_DIN_REG             (CAMERAIF_UART_TOP_BASEADDRESS+0x50)
#define CAMERAIF_UART_TOP_BAUD_RAT_REG             (CAMERAIF_UART_TOP_BASEADDRESS+0x54)
#define CAMERAIF_UART_TOP_RX_READY_COUNT_REG     (CAMERAIF_UART_TOP_BASEADDRESS+0x58)
#define CAMERAIF_UART_TOP_TIMER_WAIT_REG         (CAMERAIF_UART_TOP_BASEADDRESS+0x5C)

void ReadVideoReg(Pack *packet);
void OperateReg(SerialData *receivedData);
#endif
